spring:
  application:
    name: bentfores-goods-and-seller-management
  liquibase:
    enabled: false
    change-log: classpath:db.changelog/changelog_config.yaml

  jackson:
    default-property-inclusion: NON_EMPTY

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0 # отправляет 100% трассировок
    propagation:
      type: b3
  endpoints:
    web:
      exposure:
        include: prometheus, swagger-ui, info, metrics, health, threaddump
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

springdoc:
  swagger-ui:
    enabled: true
    useRootPath: false
    url: /openapi/bentfores-goods-and-seller-management-1.0.0.yaml
  api-docs:
    enabled: false

logbook:
  filter:
    enabled: true
  format:
    style: http
  exclude:
    - /swagger-ui/**
    - /actuator/**
    - /openapi/**
    - /index.html
    - /v3/api-docs/**

logging:
  level:
    org.zalando.logbook: TRACE
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"