---
server:
  port: 8083
  cors:
    allowed-origin-patterns:
      - '*'
    allowed-methods:
      - GET
      - POST
      - PATCH
      - PUT
    allowed-headers:
      - Authorization
      - Content-Type
      - X-Requested-With
      - Platform

spring:
  datasource:
    url: jdbc:postgresql://localhost:5442/bentfores-goods-and-seller-management
    username: bentfores-goods-and-seller-management
    password: bentfores-goods-and-seller-management

  liquibase:
    enabled: true
    user: bentfores-goods-and-seller-management
    password: bentfores-goods-and-seller-management

  jpa:
    properties:
      hibernate:
        show_sql: true

springdoc:
  swagger-ui:
    enabled: true
    useRootPath: true
    url: /openapi/bentfores-goods-and-seller-management-1.0.0.yaml
  api-docs:
    enabled: false

oauth2:
  provider-url: http://localhost:8443
  token-path: /realms/local/protocol/openid-connect/token
  client-id: swagger
  client-secret: 1234

management:
  tracing:
    enabled: false
